services:
  kombats:
    image: postgres:16
    container_name: kombats_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "kombats"
    ports:
      - "5432:5432"
    volumes:
      - ./sql:/docker-entrypoint-initdb.d


  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: kombats_rabbitmq
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
      RABBITMQ_DEFAULT_VHOST: /

volumes:
  db_data:
